version: '3.8'
services:
  nginx:
    image: nginx:1-alpine
    container_name: nginx    
    ports:
      - 80:80
    volumes:
     - ./nginx.conf:/etc/nginx/conf.d/default.conf   
     - ./html:/usr/share/nginx/html
    depends_on:
      - ollama     
    restart: always
    
  ollama:
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    ports:
      - 11434:11434
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:latest

  open-webui:
#    build:
#      context: .
#      args:
#        OLLAMA_BASE_URL: '/ollama'
#      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - 3000:8080
    env_file:
      - .env      
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'ENV=dev'
      - 'GLOBAL_LOG_LEVEL=DEBUG'
      - 'ENABLE_WEBSOCKET_SUPPORT=true'
      - 'ENABLE_OAUTH_SIGNUP=true'
      - 'ENABLE_LOGIN_FORM=false'
      - 'DEFAULT_USER_ROLE=user'
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    
volumes:
  ollama: {}
  open-webui: {}
